/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    void calculatingAveragesTest(){
        Library underTest=new Library();
        int[] num={1,2,3};
        int result=underTest.calculatingAverages(num);
        assertEquals(2,result);
    }


    @Test
    void rollTest(){
        Library underTest=new Library();
        int[] result=underTest.roll(4);
        int lingth1=result.length;
        boolean rel=false;
        assertEquals(4,lingth1);
        int[] exp={1,2,3,4,5,6};
        for (int index = 0; index < result.length; index++) {
            if(result[index]==1 && result[index]==2 && result[index]==3 && result[index]==4
            &&result[index]==5 && result[index]==6){
               rel=true;
            }
        }
        assertEquals(true,true);
    }

    @Test
    void containsDuplicatesTest(){
        Library underTest=new Library();
        String[] test={"1","test"};
        boolean result=underTest.containsDuplicates(test);
        assertEquals(false,result);
    }

    @Test
    void arrayOfArraysTest(){
        Library underTest=new Library();
        int [] result=underTest.arrayOfArrays();
        int[] exp={65, 5, 55, 52, 55, 62, 57};

        assertEquals(7,result.length);
        for (int index = 0; index < result.length; index++) {
            assertEquals(exp[index],result[index]);

        }
    }
}
