/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    void calculatingAveragesTest(){
        Library underTest=new Library();
        int[] num={1,2,3};
        int result=underTest.calculatingAverages(num);
        assertEquals(2,result);
    }


    @Test
    void rollTest(){
        Library underTest=new Library();
        int[] result=underTest.roll(4);
        int lingth1=result.length;
        assertEquals(4,lingth1);
    }

    @Test
    void containsDuplicatesTest(){
        Library underTest=new Library();
        String[] test={"1","test"};
        boolean result=underTest.containsDuplicates(test);
        assertEquals(false,result);
    }

    @Test
    void arrayOfArraysTest(){
        Library underTest=new Library();
        int [] result=underTest.arrayOfArrays();
        int[] exp={65, 5, 55, 52, 55, 62, 57};
        assertEquals(exp,result);
    }
}
