/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    void calculatingAveragesTest(){
        Library underTest=new Library();
        int[] num={1,2,3};
        int result=underTest.calculatingAverages(num);
        assertEquals(2,result);
    }


    @Test
    void rollTest(){
        Library underTest=new Library();
        int[] result=underTest.roll(4);
        boolean rel=false;
        assertEquals(4,result.length);

        int[] exp={1,2,3,4,5,6};
        for (int index = 0; index < result.length; index++) {
            for (int index1 = 0; index1 < exp.length; index1++) {
                if(result[index]==exp[index1])
                {
                    rel=true;
                }
            }

        }
        assertEquals(true,rel);
    }

    @Test
    void containsDuplicatesTest(){
        Library underTest=new Library();
        String[] test={"1","test"};
        boolean result=underTest.containsDuplicates(test);
        assertEquals(false,result);
    }

    @Test
    void arrayOfArraysTest(){
        Library underTest=new Library();
        int [] result=underTest.arrayOfArrays();
        int[] exp={65, 5, 55, 52, 55, 62, 57};

        assertEquals(7,result.length);
        for (int index = 0; index < result.length; index++) {
            assertEquals(exp[index],result[index]);

        }
    }

    @Test
    void weatherDataTest(){
        Library underTest=new Library();
        HashSet<String> result=new HashSet<>();
        HashSet<String>exp=new HashSet<>();
        result.add("the min number 51" );
        result.add("the max number 72" );
        result.add("Never saw temperature: 63");
        result.add("Never saw temperature: 67");
        result.add("Never saw temperature: 68");
        result.add("Never saw temperature: 69");
        exp=underTest.weatherData();
        assertEquals(exp,result);

    }

    @Test
    void tally(){
        Library underTest= new Library();
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String result=underTest.tally(votes);
        String exp="Bush is the winner";
        assertEquals(exp,result);

    }
}
