/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

public class Library {

    public static void main(String[] args){
//        System.out.println("hello");

        System.out.println(Arrays.toString(roll(4)));

        String[] num={"1,2,2,3","kh","ma"};
        boolean result= containsDuplicates(num);
        System.out.println(result);

        int[] num2={1,5,3,5,6};

        System.out.println(calculatingAverages(num2));
//
        System.out.println(arrayOfArrays());


    }
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int n){
        int[] RandomRoll=new int[n];

       java.util. Random rand = new Random();
        for (int index = 0; index < n; index++) {
            int randomRollNum = 1 + rand.nextInt((6 - 1) + 1);
            RandomRoll[index]=randomRollNum;
        }

        return RandomRoll;
    }

    public static boolean containsDuplicates(String[] arr){
        for (int index = 0; index < arr.length ; index++) {
            for (int s2index = index+1 ; s2index < arr.length; s2index++) {
                if(arr[index]==arr[s2index]){
                    return true;
            }

            }

        }
        return false;
    }

    public static int calculatingAverages(int[] num){

        int sum=0;
        for (int index = 0; index < num.length; index++) {
            sum +=num[index];
        }
        int avg=sum/ num.length;

        return avg;
    }

    public static int[] arrayOfArrays(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 5, 55, 52, 55, 62, 57}
        };

        ArrayList<Integer> avgs=new ArrayList<>();

        for (int[] arr:
             weeklyMonthTemperatures) {
            int avg= calculatingAverages(arr);
            avgs.add(avg);
        }

        int minArr=0;

        int min=avgs.get(0);
        for (int index = 0; index < avgs.size(); index++) {
            if(avgs.get(index)< min){
                min=avgs.get(index);

                minArr=index;
            }
        }
        return weeklyMonthTemperatures[minArr];

    }


}
