/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

     public static void main(String[] args) {


         Restaurant restaurant = new Restaurant("Mac",5,"#");
         System.out.println(restaurant);
         Review review = new Review("Nice","ayham",5);
         restaurant.addReview(review);
         Review review1 = new Review("Clean","haitham",4);
         restaurant.addReview(review1);
         Review review2= new Review("calm","laith",3); // Same Author
         restaurant.addReview(review2);

         System.out.println(restaurant);


         Restaurant restaurant2 = new Restaurant("goldenMeal",1,"#");
         Review review3 = new Review("good","aseel",4);
         restaurant2.addReview(review3);
         System.out.println(restaurant2);
    }
}
