/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


    @Test
    @DisplayName("create an instance of Restaurant and ensure that its toString is working properly.")
    void restaurantTest(){
        Restaurant restaurant=new Restaurant("goldenStar",3,2);
        String result=restaurant.toString();
        String exp="Restaurant{name= goldenStar, priceCategory='$$$', stars=2.0, restaurantReviewList=[]}";
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("create an instance of Review and ensure that its toString is working properly.")
    void reviewTest(){
        Review review=new Review("clean","yara",5);
        String result=review.toString();
        String exp="Review{body='clean', stars='5.0', author=yara}";
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("Test add review for Restaurant")
    void addReviewTest(){
        Restaurant restaurant=new Restaurant("mac",1,1);
        Review review=new Review("clean","yara",5);

        restaurant.addReview(review);

        String exp="Restaurant{name= mac, priceCategory='$', stars=5.0, restaurantReviewList=[Review{body='clean', stars='5.0', author=yara}]}";
        String result=restaurant.toString();
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("create an instance of shop and ensure that its toString is working properly.")
    void shopTest(){
      Shop shop=new Shop("moll","nice",1);

        String exp="Shop{ name=moll, description='nice', priceCategory='$', reviewList=[]}";
        String result=shop.toString();
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("Test add review for shop")
    void shopAddReviewTest(){
        Shop shop=new Shop("moll","nice",1);
        Review review=new Review("clean","yara",5);
        Review review1=new Review("clean","ali",3);

        shop.addReview(review);
        shop.addReview(review1);

        String exp="Shop{ name=moll, description='nice', priceCategory='$', reviewList=[Review{body='clean', stars='5.0', author=yara}, Review{body='clean', stars='3.0', author=ali}]}";
        String result=shop.toString();
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("create an instance of theater and ensure that its toString is working properly.")
    void theaterTest(){
        Theater theater=new Theater("movie show");

        String exp="Theater{name='movie show', movieList=[], theaterReviewList=[]}";
        String result=theater.toString();
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("Test add review for theater")
    void theaterAddReviewTest(){
        Theater theater=new Theater("movie show");
        Review review=new Review("clean","yara",5);
        Review review1=new Review("clean","ali",3);

        theater.addReview(review);
        theater.addReview(review1);

        String exp="Theater{name='movie show', movieList=[], theaterReviewList=[Review{body='clean', stars='5.0', author=yara}, Review{body='clean', stars='3.0', author=ali}]}";
        String result=theater.toString();
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("Test add review with movie name for theater")
    void theaterAddReviewMovieTest(){
        Theater theater=new Theater("movie show");
        theater.addMovie("spider name");
        theater.addMovie("spider name: no way home");
        Review review=new Review("clean","yara",5,"spider name");
        Review review1=new Review("clean","ali",3,"spider name: no way home");

        theater.addReview(review);
        theater.addReview(review1);

        String exp="Theater{name='movie show', movieList=[spider name, spider name: no way home], theaterReviewList=[Review{body='clean', stars='5.0', author=yara, movie name= spider name}, Review{body='clean', stars='3.0', author=ali, movie name= spider name: no way home}]}";
        String result=theater.toString();
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("Test add review for Restaurant")
    void updateStars(){
        // the stars rating should be the average of rating from reviews
        // 2.5+3/2=>2.8
        Restaurant restaurant=new Restaurant("mac",1,1);
        Review review=new Review("clean","yara",2.5f);
        Review review1=new Review("clean","ali",3);

        restaurant.addReview(review);
        restaurant.addReview(review1);

        String exp="Restaurant{name= mac, priceCategory='$', stars=2.8, restaurantReviewList=[Review{body='clean', stars='2.5', author=yara}, Review{body='clean', stars='3.0', author=ali}]}";
        String result=restaurant.toString();
        assertEquals(exp,result);

    }

    @Test
    @DisplayName("test for price category")
    void priceCategoryTest(){
         // user need to input number from 1-3
        // if priceCategoryInt = 1 => priceCategory="$"
        // if priceCategoryInt = 2 => priceCategory="$$"
        // if priceCategoryInt = 3 => priceCategory="$$$"
        Restaurant restaurant=new Restaurant("mac",1,1);
        Review review=new Review("clean","yara",2.5f);
        Review review1=new Review("clean","ali",3);

        restaurant.addReview(review);
        restaurant.addReview(review1);

        String exp="Restaurant{name= mac, priceCategory='$', stars=2.8, restaurantReviewList=[Review{body='clean', stars='2.5', author=yara}, Review{body='clean', stars='3.0', author=ali}]}";
        String result=restaurant.toString();
        assertEquals(exp,result);

    }



}
