/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


    @Test
    @DisplayName("create an instance of Restaurant and ensure that its toString is working properly.")
    void restaurantTest(){
        Restaurant restaurant=new Restaurant("goldenStar",3,"$$$");
        String result=restaurant.toString();
        String exp="Restaurant{name='goldenStar', stars=3, priceCategory='$$$', reviewList=[]}";
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("create an instance of Review and ensure that its toString is working properly.")
    void reviewTest(){
        Review review=new Review("clean","yara",5);
        String result=review.toString();
        String exp="Review{body='clean', stars='5', author=yara}";
        assertEquals(exp,result);
    }

    @Test
    @DisplayName("Test add review")
    void addReviewTest(){
        Restaurant restaurant=new Restaurant("mac",5,"$");
        Review review=new Review("clean","yara",5);
        Review review1=new Review("cleen","ali",3);
        Review review2=new Review("cleen","ali",2);
        Review review3=new Review("cleen","ahmad",2);
        restaurant.addReview(review);
        restaurant.addReview(review1);
        restaurant.addReview(review2);
        restaurant.addReview(review3);

        String exp="Restaurant{name='mac', stars=3, priceCategory='$', reviewList=[Review{body='clean', stars='5', author=yara}, Review{body='clean', stars='5', author=yara}, Review{body='cleen', stars='3', author=ali}, Review{body='cleen', stars='2', author=ali}, Review{body='cleen', stars='2', author=ahmad}]}";
        String result=restaurant.toString();
        assertEquals(exp,result);
    }


}
