/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    void readTest(){
        App underTest=new App();
         ArrayList<String> result= underTest.read("gates.js");
         ArrayList<String>exp=new ArrayList<>();
          exp.add(" Missing semicolon in line => 3");
          exp.add(" Missing semicolon in line => 5");

          assertEquals(exp,result);


    }

    @Test
    void emptyReadTest(){
        App underTest=new App();
        ArrayList<String> result= underTest.read("gatesEmpty.js");
        ArrayList<String>exp=new ArrayList<>();


        assertEquals(exp,result);


    }

    @Test
    void readTestNoError(){
        App underTest=new App();
        ArrayList<String> result= underTest.read("gatesNo.js");
        ArrayList<String>exp=new ArrayList<>();


        assertEquals(exp,result);


    }

}
